[package]
name = "tracing-oslog"
authors = ["Lucy <lucy@absolucy.moe>"]
version = "0.1.0"
edition = "2018"
license = "Zlib"

[dependencies]
fnv = "1.0.7"
once_cell = "1.8.0"
parking_lot = "0.11.2"
tracing-core = "0.1.20"
tracing-subscriber = "0.2.23"

[build-dependencies]
bindgen = "0.59.1"
cc = "1.0.70"

[dev-dependencies]
tokio = { version = "1.11.0", features = ["full"] }
tracing = "0.1.28"
tracing-subscriber = "0.2.23"
