[package]
name = "tracing-oslog"
description = "A layer for tracing that outputs to the oslog on macOS/iOS"
authors = ["Lucy <lucy@absolucy.moe>"]
version = "0.1.2"
edition = "2021"
license = "Zlib"
categories = ["development-tools::debugging", "development-tools::profiling", "os::macos-apis"]
keywords = ["tracing", "oslog", "os_log", "macos", "ios"]
repository = "https://github.com/Absolucy/tracing-oslog"

[dependencies]
tracing-subscriber = { version = "0.3", default_features = false, features = ["std", "registry"] }
cfg-if = "1.0"
once_cell = "1.8"
parking_lot = "0.12"
tracing-core = "0.1"

[build-dependencies]
bindgen = "0.70"
cc = "1.0"

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
targets = []
