/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mach_header {
	pub magic: u32,
	pub cputype: i32,
	pub cpusubtype: i32,
	pub filetype: u32,
	pub ncmds: u32,
	pub sizeofcmds: u32,
	pub flags: u32,
}
pub type os_function_t =
	::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
pub type os_block_t = *mut ::std::os::raw::c_void;
extern "C" {
	pub fn os_release(object: *mut ::std::os::raw::c_void);
}
extern "C" {
	pub static mut __dso_handle: mach_header;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct os_log_s {
	_unused: [u8; 0],
}
pub type os_log_t = *mut os_log_s;
pub const os_log_type_t_OS_LOG_TYPE_DEFAULT: os_log_type_t = 0;
pub const os_log_type_t_OS_LOG_TYPE_INFO: os_log_type_t = 1;
pub const os_log_type_t_OS_LOG_TYPE_DEBUG: os_log_type_t = 2;
pub const os_log_type_t_OS_LOG_TYPE_ERROR: os_log_type_t = 16;
pub const os_log_type_t_OS_LOG_TYPE_FAULT: os_log_type_t = 17;
pub type os_log_type_t = u8;
extern "C" {
	pub fn os_log_create(
		subsystem: *const ::std::os::raw::c_char,
		category: *const ::std::os::raw::c_char,
	) -> os_log_t;
}
extern "C" {
	pub fn os_log_type_enabled(oslog: os_log_t, type_: os_log_type_t) -> bool;
}
extern "C" {
	pub fn os_log_is_enabled(log: os_log_t) -> bool;
}
extern "C" {
	pub fn os_log_is_debug_enabled(log: os_log_t) -> bool;
}
pub const os_activity_flag_t_OS_ACTIVITY_FLAG_DEFAULT: os_activity_flag_t = 0;
pub const os_activity_flag_t_OS_ACTIVITY_FLAG_DETACHED: os_activity_flag_t = 1;
pub const os_activity_flag_t_OS_ACTIVITY_FLAG_IF_NONE_PRESENT: os_activity_flag_t = 2;
pub type os_activity_flag_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct os_activity_s {
	_unused: [u8; 0],
}
pub type os_activity_t = *mut os_activity_s;
extern "C" {
	pub static mut _os_activity_none: os_activity_s;
}
extern "C" {
	pub static mut _os_activity_current: os_activity_s;
}
pub type os_activity_id_t = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct os_activity_scope_state_s {
	pub opaque: [u64; 2usize],
}
pub type os_activity_scope_state_t = *mut os_activity_scope_state_s;
extern "C" {
	pub fn _os_activity_create(
		dso: *mut ::std::os::raw::c_void,
		description: *const ::std::os::raw::c_char,
		activity: os_activity_t,
		flags: os_activity_flag_t,
	) -> os_activity_t;
}
extern "C" {
	pub fn _os_activity_label_useraction(
		dso: *mut ::std::os::raw::c_void,
		name: *const ::std::os::raw::c_char,
	);
}
extern "C" {
	pub fn _os_activity_initiate(
		dso: *mut ::std::os::raw::c_void,
		description: *const ::std::os::raw::c_char,
		flags: os_activity_flag_t,
		activity_block: os_block_t,
	);
}
extern "C" {
	pub fn _os_activity_initiate_f(
		dso: *mut ::std::os::raw::c_void,
		description: *const ::std::os::raw::c_char,
		flags: os_activity_flag_t,
		context: *mut ::std::os::raw::c_void,
		function: os_function_t,
	);
}
extern "C" {
	pub fn os_activity_apply(activity: os_activity_t, block: os_block_t);
}
extern "C" {
	pub fn os_activity_apply_f(
		activity: os_activity_t,
		context: *mut ::std::os::raw::c_void,
		function: os_function_t,
	);
}
extern "C" {
	pub fn os_activity_scope_enter(activity: os_activity_t, state: os_activity_scope_state_t);
}
extern "C" {
	pub fn os_activity_scope_leave(state: os_activity_scope_state_t);
}
extern "C" {
	pub fn os_activity_get_active(
		entries: *mut os_activity_id_t,
		count: *mut ::std::os::raw::c_uint,
	) -> ::std::os::raw::c_uint;
}
extern "C" {
	pub fn os_activity_get_identifier(
		activity: os_activity_t,
		parent_id: *mut os_activity_id_t,
	) -> os_activity_id_t;
}
extern "C" {
	pub fn _os_activity_start(
		dso: *mut ::std::os::raw::c_void,
		description: *const ::std::os::raw::c_char,
		flags: os_activity_flag_t,
	) -> os_activity_t;
}
extern "C" {
	pub fn os_activity_end(activity: os_activity_t);
}
extern "C" {
	pub fn _os_activity_set_breadcrumb(
		dso: *mut ::std::os::raw::c_void,
		name: *const ::std::os::raw::c_char,
	);
}
extern "C" {
	pub fn wrapped_os_log_with_type(
		log: os_log_t,
		type_: os_log_type_t,
		message: *const ::std::os::raw::c_char,
	);
}
extern "C" {
	pub fn wrapped_os_log_default() -> os_log_t;
}
